# -*- coding: utf-8 -*-
"""adcAgent_Testing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lf1GJLS-KWfIhiCDnkZZVAf53ITHmwP7
"""

# !pip install biopython
# !pip install -U langgraph langchain langchain-openai langchain-community tavily-python

# # Commented out IPython magic to ensure Python compatibility.
#  # 1. Install system-level dependencies (HMMER is required by ANARCI)
# !apt-get update
# !apt-get install hmmer -y

# # 2. Ensure your Python build environment is up to date
# !pip install --upgrade setuptools wheel biopython

# # 3. Install Fair-ESM (Evolutionary Scale Modeling)
# !pip install fair-esm

# # 4. Install standard bioinformatics utilities
# !pip install biopython torch

# # get anarci ready
# # 1. Clone the repository
# !git clone https://github.com/oxpig/ANARCI.git

# # 2. Install dependencies via pip and apt (faster and more stable on Colab than Conda)
# !pip install biopython
# !apt-get install -y hmmer

# # 3. Build MUSCLE 3.8.31 from source
# # %cd /content
# !mkdir -p muscle
# # %cd muscle
# !wget https://drive5.com/muscle/downloads3.8.31/muscle3.8.31_src.tar.gz
# !tar xzvf muscle3.8.31_src.tar.gz
# # %cd muscle3.8.31/src/
# # Note: On modern Linux, we often need to fix a common 'make' issue for this old version
# !make

# # 4. Test and Move MUSCLE to ANARCI bin
# !./muscle -version
# !cp muscle /content/ANARCI/bin/muscle
# # Verify the replacement
# !ls -l /content/ANARCI/bin/muscle

# # 5. Finish ANARCI Installation
# # %cd /content/ANARCI
# !python setup.py install

# 6. Final verification
import os
import sys
# Adding the installation path to sys.path if needed
sys.path.append('/content/ANARCI')
try:
    import anarci
    print("ANARCI successfully imported!")
except ImportError:
    anarci = None
    print("ANARCI not available — skipping (not required for API-based sequence retrieval)")

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# %pip install langchain-openai==0.3.10
# %pip install langchain==0.3.21
# %pip install openai==1.68.2
# %pip install langchain-community==0.2.1
# %pip install  --upgrade langgraph
# %pip install langchain_community==0.3.24

import os
import json
import getpass
from typing import List, Dict
from pydantic import BaseModel, Field
from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_core.messages import HumanMessage, AIMessage, ToolMessage, BaseMessage
from langchain_community.utilities.tavily_search import TavilySearchAPIWrapper
from langchain_community.tools.tavily_search import TavilySearchResults
from langchain_openai import ChatOpenAI
# NOT CALLED (revision cleanup): MessageGraph is never referenced anywhere
# in this file (StateGraph is what's actually built, near the bottom).
# The `END` import here is also redundant -- the only place END is actually
# used (builder.add_edge("Result Presenter", END)) comes after a second,
# later `from langgraph.graph import StateGraph, START, END` import.
# from langgraph.graph import END, MessageGraph
from langchain_core.utils.function_calling import convert_to_openai_function
import os, json, re
from typing import List, Dict, Any, Sequence, TypedDict, Annotated
from typing import TypedDict, Annotated, List, Union
import operator
from langchain_core.messages import BaseMessage
import operator
from langchain_core.messages import BaseMessage, AIMessage, HumanMessage

try:
    from langchain_core.tools import tool
    print("✅ tool imported from langchain_core.tools")
except Exception:
    # Fallback for some installs
    from langchain.tools import tool
    print("✅ tool imported from langchain.tools (fallback)")


# --- moved here from original script body (env/client setup that lived
# between MasterState and the clinical prompt template) ---
def _set_if_undefined(var: str) -> None:
    if os.environ.get(var):
        return
    os.environ[var] = getpass.getpass(var)
_set_if_undefined("TAVILY_API_KEY")
_set_if_undefined("OPENAI_API_KEY")

tavily_tool=TavilySearchResults(max_results=1)

import os

llm = ChatOpenAI(model="gpt-4.1-nano")

revise_instructions = """Revise your previous analysis with the rigorous scrutiny of a Clinical Oncologist and Molecular Immunologist.
- **Incorporate Critique:** Address the previous self-reflection to tighten the technical discussion on paratope-epitope interactions and therapeutic efficacy.
- **Evidence & Citations:** You MUST include numerical citations [1, 2] referencing Phase I-III clinical trials, high-impact meta-analyses, or structural biology papers (e.g., Nature Reviews Cancer, JCO).
- **Statistical Rigor:** Distinguish between surrogate endpoints (e.g., Progression-Free Survival) and Overall Survival. Explicitly mention p-values or Hazard Ratios (HR) if referencing specific trials.
- **Biomarker Integration:** Address patient-specific variables such as antigen expression density (IHC/FISH scoring), circulating tumor DNA (ctDNA), or cytokine profiles (e.g., IL-6, TNF-alpha) regarding cytokine release syndrome risk.
- **Structural Precision:** Ensure claims regarding antibody isotype (e.g., IgG1 vs IgG4) and Fc-gamma receptor binding are supported by mechanistic evidence.
- **References Section:** Provide a formal bibliography at the bottom:
  [1] Author, Paper Title, Journal (Year).
  [2] Author, Paper Title, Journal (Year).
- **Constraint:** Maintain a strict limit of 250 words. Prioritize data density and mechanistic clarity over narrative prose.
"""
